name: Create Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - 'master'
  
permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Set Release version env variable
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Build with Maven
        run: |
          mvn --batch-mode --update-snapshots --also-make clean package

      - name: Provide files
        run: |
          mkdir "${RUNNER_TEMP}/dist"
          cp pom.xml "${RUNNER_TEMP}/dist/${GITHUB_REPOSITORY#*/}-${{ env.RELEASE_VERSION }}.pom"
          echo "pwd:"
          pwd
          echo "ls ${RUNNER_TEMP}/dist:"
          ls "${RUNNER_TEMP}/dist"
          echo "ls:"
          ls
          echo "ls target:"
          ls target
          echo "cp:"
          cp "target/*-${{ env.RELEASE_VERSION }}.jar" "${RUNNER_TEMP}/dist"

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --draft --prerelease \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/}-${{ env.RELEASE_VERSION }}" \
              --generate-notes \
              "${RUNNER_TEMP}/dist/*"

#      - name: Upload files
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          tag: ${{ github.ref_name }}
#        run: |
#          gh release upload "$tag" --clobber "${RUNNER_TEMP}/${GITHUB_REPOSITORY#*/}-${{ env.RELEASE_VERSION }}.pom" target/*.jar
